### ISSUE TITLE
Missing Citation

### ISSUE THREAD

**Issue by yiranzhong** [ardaduz/deep-video-mvs#1]
Hi Arda,

I just come across this work. It is a very nice paper.

However, there is a very closely related work (Open-World Stereo Video Matching with Deep RNN. ECCV18) is missing in the reference as both methods are using convLSTM on the bottleneck of the matching network. 

There are some differences between these two and it would be nice to clarify them in the paper.

Thanks,
Yiran

**Comment by ardaduz** [comment]
Thank you for pointing it out. I will include it in a revised version in the future.
