### ISSUE TITLE
The split of scannet dataset

### ISSUE THREAD

**Issue by ckLibra** [ardaduz/deep-video-mvs#12]
Hi,  Thanks for your great work! I have one question about the split of scannet. According to the train and validation.txt in your scannet-export folder, it seems a little different from https://github.com/xxlong0/ESTDepth/tree/main/data/scannet_split. I wonder which is the official split of the scannet.

**Comment by ardaduz** [comment]
Hi,

Our training/validation scene splits are randomly created while preparing the dataset (please see lines 248-279 [here](https://github.com/ardaduz/deep-video-mvs/blob/master/dataset/scannet-export/scannet-export.py#L248)). As we noticed the splits given out by ScanNet authors at late stage in our work, we kept our random splits and I shared them for reproducibility of our experiments. Official ScanNetV2 test split is fixed for everyone: scene0707_00 to scene0806_00. 

As far as I see, ESTDepth uses the splits produced by the ScanNet authors (compare [here](https://github.com/ScanNet/ScanNet/blob/master/Tasks/Benchmark/scannetv2_train.txt) and [here](https://github.com/xxlong0/ESTDepth/blob/main/data/scannet_split/train_split.txt)).

Hope this clarifies any confusion.

**Comment by ckLibra** [comment]
Thanks for your patient answer! It is very helpful.
