### ISSUE TITLE
Cameras with Fixed Position

### ISSUE THREAD

**Issue by arazvant** [ardaduz/deep-video-mvs#15]
Hello,

Really great work!

I've wanted to ask, would this model work based on the video input from 2 static cameras?
Let's say I have two fixed in place cameras, and the only thing moving are the contents in front of the camera.

**Comment by ardaduz** [comment]
Hi,

This work is aimed at multi-view stereo with moving camera in static scenes, so it's not really suitable for your operating case out-of-the box. But the ideas presented in the paper like having a recurrent cell at the bottleneck to increase temporal consistency among two-camera stereo depth predictions hopefully inspires you when you're coming up with your solution.
