### ISSUE TITLE
Fusion network training. Pretrained PairNet Decoder?

### ISSUE THREAD

**Issue by mohammed-amr** [ardaduz/deep-video-mvs#17]
Hello,

I just need to confirm the training strategy with the decoder when reproducing your results. You mention in the paper that pretrained PairNet weights at 100k are loaded for the feature extractor, FPN, and the cost volume encoder. Are the decoder's weights initialized from scratch? 

![image](https://user-images.githubusercontent.com/14994206/152990104-a8919b7d-474e-43bf-a3c6-df52b6ed7279.png)

Thanks!

**Comment by ardaduz** [comment]
Yes, ConvLSTM and decoder are initialized with random weights from scratch with default random strategy, i.e. you don't have to do anything.

**Comment by mohammed-amr** [comment]
Thanks for your reply! 

`i.e. you don't have to do anything.` What do you mean by this? I've had to modify the fusionnet training script [here](https://github.com/ardaduz/deep-video-mvs/blob/fa14288f149c5af7b2a49092f729f5c4f44517ba/dvmvs/fusionnet/run-training.py#L104) to accept only certain checkpoint files (feature extractor, FPN, encoder) from PairNet training at 100k steps. 

Thanks!

Post edit: ah, you mean random init for them and not having to load checkpoints. Understood. I'll wait for an ack from you and close the issue. Thanks!

**Comment by ardaduz** [comment]
Your edit is right, I was talking about not touching the random init.

You could also only place (forcing alphabetical order): 0_feature_extractor, 1_feature_pyramid, 2_encoder in the weights folder, and don't place anything else. If the weights for a module is not found in the folder, the code skips loading the weights for that module.

Anyway, as long as you can load for only feature extractor, FPN, encoder from pairnet training checkpoints, it does not matter how you do it.

**Comment by mohammed-amr** [comment]
Great, thanks for your help!
