### ISSUE TITLE
7Scenes Depth and RGB Intrinsics/focal lengths

### ISSUE THREAD

**Issue by mohammed-amr** [ardaduz/deep-video-mvs#19]
Hello, 

How do you handle the difference in focal lengths between the RGB and depth maps for 7Scenes? Are you cropping the RGB images down to match depth or reprojecting depths given the intrinsics of both? 

Thanks!

**Comment by ardaduz** [comment]
Hi,

As we mention in the paper Section 4.1:

"The official distribution of [16] does not supply aligned color and depth images, so we use the rendered depth maps provided by [7] for evaluation."

You can check this out: https://github.com/vislearn/LessMore#data-structure

**Comment by mrharicot** [comment]
Hi,
Ah we missed this in the paper, thanks!
