### ISSUE TITLE
Can you provide the meshes of your method and the baseline methods on ScanNet and 7Scenes?

### ISSUE THREAD

**Issue by NoOneUST** [ardaduz/deep-video-mvs#21]
Can you provide the meshes of your method and the baseline methods on ScanNet and 7Scenes? Thank you so much!

**Comment by ardaduz** [comment]
I do not have them stored anymore. But once you have the input data and predictions structured like this: https://github.com/ardaduz/deep-video-mvs/tree/master/sample-data, you can produce the meshes using https://github.com/ardaduz/deep-video-mvs/blob/master/sample-data/run-tsdf-reconstruction.py. Some instructions are here: https://github.com/ardaduz/deep-video-mvs#tsdf-reconstructions. 

Everything you need to get the meshes is in this repository:
- a script to create the keyframe indices (https://github.com/ardaduz/deep-video-mvs/blob/master/dvmvs/simulate_keyframe_buffer.py)
- the prediction pipelines of the our method and the baseline methods, that are suitable to be run with the generated keyframe indices (https://github.com/ardaduz/deep-video-mvs/tree/master/dvmvs/baselines)
- a script to generate the meshes using TSDF fusion out of the predictions (https://github.com/ardaduz/deep-video-mvs/blob/master/sample-data/run-tsdf-reconstruction.py)

Let me know if something is not clear.

**Comment by NoOneUST** [comment]
Hi, thanks so much for your reply. Did you test other metics on ScanNet and 7Scenes? For example, absolute relative error, absolute difference, and squared relative loss?
![1652717453(1)](https://user-images.githubusercontent.com/48406286/168636951-4d93f0f0-ef25-40e9-b9d0-b926270f77a3.png)

**Comment by ardaduz** [comment]
Please check the paper.

We have Abs Rel, Abs Diff and delta < 1.25 metrics. Also, we evaluate Abs Inv, since that is our loss function.
