### ISSUE TITLE
Depth scale of RGBD Scene V2

### ISSUE THREAD

**Issue by thuzhaowang** [ardaduz/deep-video-mvs#8]
Thanks for your great work!

I'm currently working on MVS and evaluate methods on RGBD Scene V2 dataset. But I found the depth image, saved in 16-bit image, is not in the millimeter (1000) scale. So may I ask what's the right scale value to have the real world depth?

Best,
Wang

**Comment by ardaduz** [comment]
Hi Wang,

[Here](https://github.com/ardaduz/deep-videos/tree/master/dataset), I placed some code to help exporting all the datasets in a standardized form as this work consumes them. 

[This script](https://github.com/ardaduz/deep-video-mvs/blob/master/dataset/rgbdscenes-export/rgbdscenes-export.py) is for RGBD Scenes V2:
The original depth (official distribution of the data) is first divided by 1e4 to get the depth in meters, cleaned up and then converted to milimeter scale. You can verify this scale by building the corresponding point cloud using [this script](https://github.com/ardaduz/deep-video-mvs/blob/master/dataset/build_point_cloud.py).

Hope this helps!

**Comment by thuzhaowang** [comment]
Many thanks for your quick and kind reply! That really helps.
