### ISSUE TITLE
Code to generate mesh as the mp4 shows

### ISSUE THREAD

**Issue by fengting-amazon** [ardaduz/deep-video-mvs#9]
Hi, 

Thank you for sharing the code of your great work. 

I wonder if there is any code that can help us to generate the mesh from the depth as the attached mp4 show. It would be even more perfect if it can directly provides the interface like that, and fuse the depths into a mesh in such an online fashion .

**Comment by ardaduz** [comment]
Hi, 

I added the required code, some sample input/outputs and a [section](https://github.com/ardaduz/deep-video-mvs/#tsdf-reconstructions) to the end of README.

The depth map integration is not a sophisticated online algorithm, I just run marching cubes on the whole volume after each depth integration and save the mesh, making it "online". The script I provide gives you an option (--save_progressive flag) to save those meshes after integrating each predicted depth map.

Hope this helps.

**Comment by fengting-amazon** [comment]
Thank you. It helps, will take a look.
